# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HMSDTMKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'HiAnalytics'

  target 'HMSDTMKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HMSDTMKitDemoUITests' do
    # Pods for testing
  end

end
